name: Deploy GitBook to GitHub Pages

on:
  push:
    branches:
      - zdocs  # 根据实际分支修改

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 建议使用 LTS 版本
          cache: 'npm'

      - name: Install and Build
        run: |
          npm install honkit --save-dev
          npx honkit build # 构建

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
